version: '3.8'
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  node-app:
    build: artifacts/gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'