# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test with Postgress

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests-with-potgress:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose-postgress.yml up -d --force-recreate
    - name: Wait for containers start
      run: sleep 30					
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11		
    - name: Start aqa-shop
      run: sudo java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/postgres -jar artifacts/aqa-shop.jar &		
    - name: Wait for aqa-shop start
      run: sleep 30	
    - name: Check for aqa-shop's respond
      run: sudo curl localhost:8080		
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test -Ddb.url=jdbc:postgresql://localhost:5432/postgres  -Dlogin=app -Dpassword=pass -Dapp.url=http://localhost:8080 -Dselenide.headless=true
